#server:
#  port: 8081
#
#spring:
##  datasource:
##    url: jdbc:mysql://localhost:3306/doctorcareweb
##    username: root
##    password: root
#
##    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:mysql://mainline.proxy.rlwy.net:15654/railway
#    username: root
#    password: KqdjSVUptjvQtOjtUfzEeBGScVDevEEI
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true


server:
  port: ${PORT:8081}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
